add_newline = true

format = """
$username\
    [](fg:#313244 bg:#cba6f7)\
    $directory\
    [](fg:#cba6f7 bg:#f5c2e7)\
    $git_branch\
    [](fg:#f5c2e7 bg:none)\
    $git_status\
    $character\
    """
    right_format = """$time
    """
    [username]
    show_always = true
    format = "[  $user@host ](bg:#313244 fg:#cba6f7 bold)"

    [directory]
    truncation_length = 3
    truncate_to_repo = false
    truncation_symbol = "…/"
    format = "[ 󰉋 $path ](bg:#cba6f7 fg:#2D353B bold)"

    [git_branch]
    symbol = " "
    format = "[ $symbol$branch](bg:#f5c2e7 fg:#2D353B bold)"

    [git_status]
    style = "fg:#E67E80 bold"
    modified = "!"
    staged = "+"
    untracked = "?"
    deleted = "✘"
    renamed = "»"

    [character]
    success_symbol = "[ ∼ ](bold #D699B6)"
    error_symbol = "[ 󰅖 ](bold #E67E80)"

    [time]
    disabled = false
    time_format = "%H:%M"
    format = "[  $time ](fg:#3A94C5)"
