add_newline = false
format = """\
$username\
$directory\
$git_branch\
$git_status\
$character
"""
    right_format = """$time"""

    [username]
    show_always = true
    style_user = "fg:black bg:bright-black bold"
    format = "[ $user@host ]($style)(fg:blue bg:green)[▕](fg:yellow bg:bright-black)"

    [directory]
    style = "fg:black bg:green bold"
    truncation_length = 3
    truncate_to_repo = false
    format = "[ $path ]($style)(fg:green bg:bright-black)[▕](fg:yellow bg:green)"

    [git_branch]
    symbol = " "
    style = "fg:black bg:purple bold"
    format = "[ $symbol$branch ]($style)"

    [git_status]
    style = "fg:red bold"
    modified = "!"
    staged = "+"
    untracked = "?"
    deleted = "✘"
    renamed = "»"
    format = "[$all_status$ahead_behind]($style)"

    [character]
    success_symbol = "[ ✔ ](fg:blue bold)"
    error_symbol = "[ ✘ ](fg:red bold)"

    [time]
    disabled = false
    time_format = "%H:%M"
    style = "fg:#d8dee9"
    format = "[$time]($style)"
