#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#AutoStart application
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
~/.fehbg &
dunst &
polybar &
fcitx5 &

killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 0.2; done
polybar main &
